### ISSUE TITLE
[1.16.4]{Forge} Modpack will not load when this is added

### ISSUE THREAD

**Issue by ProsperCraft** [CorgiTaco-Archive/lazydfu#1]
Modpack- TownCraft TWO for 1.16.5 version .31

https://gist.github.com/ProsperCraft/3f700566027d2aa280234f0dc1765065

**Comment by TelepathicGrunt** [comment]
Do you have DataFixerSlayer on or anything else that messes with DataFixerUpper?

**Comment by TelepathicGrunt** [comment]
Hmm. I didn't get a crash when using `TownCraft TWO for 1.16.5-0.34.zip` with LazyDataFixerUpper. Is there any other mod that you have put on besides what is in TownCraft?
![image](https://user-images.githubusercontent.com/40846040/112662062-9f2b0000-8e2d-11eb-905f-5cd8f13050ba.png)

**Comment by TelepathicGrunt** [comment]
Looking at the logs, it could be RandomPatches with their fake data fixer which can break structure mods/datapacks

```
[26Mar2021 12:25:40.964] [modloading-worker-8/ERROR] [structurize/]: ----------------------------------------------------------------- 
 Invalid DataFixer detected, schematics might not paste correctly! 
The following DataFixer was added: class com.therandomlabs.randompatches.util.FakeDataFixer
-----------------------------------------------------------------
```

**Comment by ProsperCraft** [comment]
Interesting, so is this doing the same as your mod?  are there advantages to disabling the option in Randompatches and using yours?

**Comment by TelepathicGrunt** [comment]
I do not know what's random patches does but from the name, it sounds like they disable DFU by replacing it with an empty one. 

Doing so may break the structure nbt files from some mods or datapacks if their structure files are still using an old format. DFU is able to convert them into the newer format on the fly and allow their structures to spawn. But with mods that disable or replace DFU, the other mods/datapack's files cannot get updated and so, those structures or datapacks implodes and doesn't work. 

I just had to deal with this myself as DataFixerSlayer, which disabled DFU, made my mod's structure compat datapack break and my swamp village to not spawn anything.

LazyDataFixerUpper aims to simply delay the DFU until it actually needed. That way you still get the faster start time since DFU takes a bit of time to run. But when the games hits a file that needs to be updated, LazyDataFixerUpper will then allow DFU to run and update the files so that nothing breaks.

**Comment by TelepathicGrunt** [comment]
Also, just wanted to clarify, I'm not the dev of this mod lol. Just a friend modder passing by

**Comment by randogaming6252** [comment]
if youre using create, like literally just default create without any of the addons, its completely incompatible and a fix is not planned for the older versions any time soon as its a non issue on new versions. it causes a render thread crash with both create and lazydfu installed solo
