### ISSUE TITLE
[question] what is the difference between LazyDFU and disabling DFU with RandomPatches?

### ISSUE THREAD

**Issue by Wedge1453** [CorgiTaco-Archive/lazydfu#4]

**Comment by Jonathing** [comment]
It's all in the README in both this fork and the main project. LazyDFU makes it so that the DFU rules are *not* calculated at runtime, while disabling the DFU entirely will just kill the DFU and anything in your world that might have defunct data from an old version or mod will just break. This is why killing the DFU destroys structures from some mods, even if the mod is for 1.16.5 and the structures were saved in 1.16.4.
