### ISSUE TITLE
1.19.2 Forge Versions 43.1.65 to 43.2.0 none functional

### ISSUE THREAD

**Issue by Zelioth** [CorgiTaco-Archive/lazydfu#9]
Testing updates for my mod pack I have found that when updating to forge versions 43.1.65 and 43.2.0 the mod pack closes with a error code 1. This also doesn't allow anything to initialize or log any information in the debug or log file. So out of 493 mods included in my mod pack I came down to one that when removed allows the pack to launch fine on those forge versions.

Friends United Forge 1.19.2 
Latest Working Forge version 43.1.64

Reason for finding issue :  

Updating mod pack to latest forge versions created an error code 1 when launching 

Fix : 

Removing Lazy DFU from the pack and updating forge allowed the pack to launch and function correctly.

**Comment by IGCBOOM** [comment]
Same, getting this error.
`Info Exception in thread "main" java.lang.IllegalArgumentException: 1.0-1.19+: Empty pre-release`

Seems to be due to an invalid version, [link to forge thread.](https://forums.minecraftforge.net/topic/118938-forge-4320-minecraft-1192-exception-in-thread-main-javalangillegalargumentexception-10-119-empty-pre-release/)

**Comment by HexedHero** [comment]
Remove the "+" symbol from the jar file name.

**Comment by DeshiDesu** [comment]
> Remove the "+" symbol from the jar file name.

Will you update the file on Curseforge? Curseforge modpacks will keep installing the files with the "+" symbol, regardless we remove it or not.

**Comment by ghost** [comment]
Looks like the issue is what @HexedHero is saying. The goofy "+" at the end of the mod is causing it to bork.

**Comment by DeshiDesu** [comment]
wheres the mod authors when there's a serious critical issue at hand

**Comment by WarpZephyr** [comment]
Can confirm I am getting this error as well

**Comment by JustJinxed** [comment]
This started being an issue between Forge versions 43.1.64 -> 43.1.65 and as of 43.2.3 (on 1.19.2) it's still there. LexManos is aware of it, but I don't see it mentioned on their github as being a "bug" yet. 

re: https://forums.minecraftforge.net/topic/118938-forge-4320-minecraft-1192-exception-in-thread-main-javalangillegalargumentexception-10-119-empty-pre-release/

I've asked them for some clarification. At least if forge is going to take a hardline in naming conventions, fml should likely quietly ignore and skip mods with malformed names instead of holding up the entire load because one author stuck a symbol where it don't belong. 

Quick fix, remove the + and/or use proper semantic versioning (https://semver.org) so forge doesn't hiccup on load.

**Comment by CorgiTaco** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge/files/4327266

**Comment by DeshiDesu** [comment]
ONG OUR LORD AND SAVIOR
